import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { redirect } from "next/navigation";
// import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh`}>
        <header className="h-16 px-6 border-b flex item-center">
          <Button asChild variant="ghost">
            <Link href="/">un bijour - shiruME</Link>
          </Button>
          <span className="" />
          <form
            className="flex gap-2"
            action={async (data: FormData) => {
              "use server";
              const keyword = data.get("keyword") as string;

              const params = new URLSearchParams();
              params.append("q", keyword);

              redirect(`/search?${params.toString()}`);
            }}
          >
            <Input autoComplete="off" name="search" className="flex-1" />
            <Button type="submit" size="icon">
              <Search size={20} />
            </Button>
          </form>
        </header>
        <main className="py-10 container">{children}</main>
        <footer className="h-16 px-6 border-t flex item-center sticky top-full text-sm">&copy; 2024 un bijour - shiruME</footer>
      </body>
    </html>
  );
}
